{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include ".helm.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include ".helm.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include ".helm.serviceAccountName" . }}
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - pod
    verbs:
      - watch
      - get
      - list
      - update
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include ".helm.serviceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include ".helm.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include ".helm.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---
{{- end }}
